### ISSUE TITLE
Downloads page not up to date

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit.github.io#103]
The downloads page doesn't list the latest versions of several of our products, e.g.: NUnit Console 3.12 and NUnit Test Adapter 3.17.

The links themselves actually go to the latest release. Is there any way we can automatically pick up the names and display them?

As a short term fix, the text should be updated. It's a simple change but I hesitate to do it myself since I'm not set up to display the changes locally.

**Comment by mikkelbu** [comment]
I can do an update of all the releases (Rob has made it, so that it is possible to see the changes locally using a docker image). 

Regarding automatic this, then we could follow the `latest` redirect to the actual page - e.g. https://github.com/nunit/nunit/releases/tag/v3.13.2. From this url we know the version number (hopefully it corresponds to the tag). It is also possible to extract the date, but then we are depending on they don't change the presentation or the html element `local-time` which seems a bit brittle. It would probably be easier to call a github API for this, but it also seem a bit overkill (although we often forget to update the download page)
