### ISSUE TITLE
All NUnit 2.x documentation links take you to a 404 page

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit.github.io#79]
/cc @rprouse
Not sure if this is related to changes made for our new docs, so looping in @SeanKilleen.

All 2.x links on https://nunit.org/documentation/ take you to URLs like https://docs.nunit.org/2.6.4/docHome.html with 404s:

![image](https://user-images.githubusercontent.com/8040367/85962760-73ebb100-b980-11ea-97de-4b8c4f0c9e4e.png)

**Comment by SeanKilleen** [comment]
@jnm2 thanks for bringing this to my attention. This indeed appears to be a breaking change because GitHub's DNS and hosting is having trouble hosting both `nunit.org/docs/*` and `docs.nunit.org` due to the overlap of docs.

This is unfortunate; GitHub support confirmed that this should have been fine.

Rob is away at the moment but I can see a few courses of action here:

1. Temporarily take the docs site down. This will restore the old docs links once DNS updates. Depending on the audience for the old docs, this might be what we need to do and I'm OK with it. We haven't published it anywhere yet.
2. I could rename this GitHub repository to something like `thedocs` (to ensure it doesn't conflict with other similar terms), in which case github would handle all the repo-level stuff for us and nothing should be an issue. I am not sure that it will solve the problem if github's helpful handling of redirects keeps the issue in place.
3. I could do a quick PR capturing the old documentation and moving it to docfx as-is -- e.g. telling docfx to copy the raw html files and not modify them in any way. I believe the result will be that it looks as it does now.

I'm thinking that I will start on a PR for item 3 in case it is needed.

@jnm2 @CharliePoole do you have thoughts on how we should proceed with this in Rob's absence? I know he said he was out for a few days.

**Comment by SeanKilleen** [comment]
In the interest of preserving existing material over new stuff, I am going to attempt to take the docs site offline in the hopes that this resolves the conflict for the time being.

**Comment by jnm2** [comment]
That sounds good. Thanks for being willing to do something so quickly! 3 sounded good if that ends up being a way to keep the old links working without giving up the `docs.nunit.org` domain.

**Comment by SeanKilleen** [comment]
The symptom of this issue should be resolved for now. 

We can revisit publishing the docs site once I've ported the legacy docs as-is to the site and have gotten @rprouse's OK that he's comfortable to proceed that way.

**Comment by SeanKilleen** [comment]
Again, great catch @jnm2 -- I'm glad we didn't have this as an issue for too long. Stability is important to me 👍

**Comment by jnm2** [comment]
It was dumb luck. I was there to confirm whether NUnit was originally copyright 2000 or 2001. 2000, it turns out. 😀
Thanks for your help!

**Comment by CharliePoole** [comment]
Wondering why this is closed if only the immediate issue is solved.

Anyway, see my comment on /nunit/docs#41about the copy of the docs on the nunit-legacy site.

**Comment by jnm2** [comment]
Sorry, shall I reopen? I was judging by the location and title that this issue only tracked the immediate problem.

**Comment by jnm2** [comment]
Never mind, I see that Sean moved the outstanding question to https://github.com/nunit/docs/issues/441.
